spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/zipon}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ai:
  base-url: http://localhost:8000

cloud:
  aws:
    s3:
      bucket: zipon-media
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
app:
  s3:
    expose: presigned #pbulic

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.apache.coyote.http11: DEBUG

# Elasticsearch 설정
elasticsearch:
  host: localhost
  port: 9200
  index:
    property: my_index