spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql:${DB_URL://localhost:5432/zipon}?serverTimezone=Asia/Seoul&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

ai:
  base-url: http://localhost:8000

cloud:
  aws:
    s3:
      bucket: dfsfsf
    region:
      static: ap-east-1
    credentials:
      access-key: sdfsdf
      secret-key: sdfsdfsd


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.apache.coyote.http11: DEBUG

# Elasticsearch 설정
elasticsearch:
  uris: http://localhost:9200