spring:
  application:
    name: a303-backend

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:dev-secret-key-dev-secret-key-dev-secret-key}
  access-token-hours: 24
  refresh-token-days: 14

instant-minute: 15

frontUrl: ${FRONT_URL:http://localhost:3000}

ssafy:
  api:
    url: ${SSAFY_API_URL}
    key: ${SSAFY_API_KEY}
gov:
  api:
    url: http://api.odcloud.kr/api/nts-businessman/v1
    key: ${GOV_API_KEY}

bizno:
  url: https://bizno.net
  key: ${BIZNO_API_KEY}

elasticsearch:
  host: localhost
  port: 9200
  index:
    property: my_index